### ISSUE TITLE
Adapter bekommt keine Verbindung

### ISSUE THREAD

**Issue by chucky6661902** [Ax-LED/ioBroker.powerfox2#3]
Powerfox versucht sich zu verbinden , aber bekommt keine .
Diese Meldung kommt immer 

`instance system.adapter.powerfox2.0 already running with pid 1841…
 
`
Über das App funktioniert alles 

**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by Ax-LED** [comment]
@chucky6661902 
hast du Sonderzeichen im Passwort?
Falls ja, probiere mal das Passwort zu ändern.
Gruß
AxLED

**Comment by Ax-LED** [comment]
@chucky6661902 
hast du mal den iobroker neu gestartet? Habe Powerfox selbst im Einsatz und bei mir geht alles.

Gruß 

AxLED

**Comment by chucky6661902** [comment]
Danke läuft wieder . Keine Ahnung warum ?

**Comment by Ax-LED** [comment]
closed

**Comment by chucky6661902** [comment]
Hallo 
Leider kommt das Problem wieder und kann nur mit einem Server Neustart behoben werden .
Kann ich etwas einstellen , damit diese Probleme nicht mehr kommen ?

**Comment by blebbens** [comment]
Habe selbiges Problem... neues Passwort, ioBroker Neustart... keine Besserung.

**Comment by Ax-LED** [comment]
@chucky6661902 
@blebbens 

aufgrund der Tatsache dass der Adapter bei Euch bereits ging (und bei mir täglich läuft und weiterhin funktioniert) denke ich nicht dass es am Adapter generell liegt.
Was passiert beim Aufruf der folgenden URL ({device} durch eure Device Nr. tauschen) ?:  https://backend.powerfox.energy/api/2.0/my/{device}/current

Das ist die URL die der Adapter abruft. Kann aber auch sein dass sich ioBroker ab und zu mal verschluckt.

Gruß

AxLED

**Comment by chucky6661902** [comment]
Ist das richtig das ein cron von 1 min eingestellt ist ? Der Adapter startet jede Minute neu
