### ISSUE TITLE
Timeout for await axios missing

### ISSUE THREAD

**Issue by The2Earthlings** [Ax-LED/ioBroker.powerfox2#4]
As it now happened several times on my installation that there was no response but open http request to powerfox (which caused that the next request was not able as old process still alive) it would be great to add the timeout feature to the axios request to "kill it":
timeout: x

like: 
await axios({
            method: 'post',
            url: '/',
            **timeout: 10000 // only wait for 10s**
        })

Ideally the timeout is configurable in Admin UI (or e.g. alternatively set to 10000?)

thx
Norbert

**Comment by Ax-LED** [comment]
@The2Earthlings 
i am not a professional programmer, so i dont know if your hint works. Have you tested it?
AxLED

**Comment by HarryDN** [comment]
tested it with timout parameter for about 4 weeks now, seems to work! :) 
Thx

**Comment by Ax-LED** [comment]
@The2Earthlings 

you can try powerfox2 version 0.0.13 from github, i implemented the timeout as you suggested.

AxLED

**Comment by Ax-LED** [comment]
@The2Earthlings 

should be fixed with version 0.0.14 in stable repository of iobroker

AxLED
