### ISSUE TITLE
Regelmäßige Error-Meldungen bei iorboker

### ISSUE THREAD

**Issue by rastal7707** [Ax-LED/ioBroker.powerfox2#7]
Hallo zusammen,

ich habe im Log regelmäßig die nachfolgende Error-Meldung:

`powerfox2 error: Error: undefined is not a valid state value`

Die Meldung erscheint jede Minute. Der Sensor ist dauerhaft verbunden und in der Powerfox App werden auch dauerhaft Daten gesendet.

Viele Grüße
Matthias

**Comment by Ax-LED** [comment]
@rastal7707 
kannst du bitte mal die Instanz im iobroker auf "debug" stellen und mir die log ausgabe von powerfox für einen Durchlauf zeigen?

AxLED

**Comment by Ax-LED** [comment]
mangels Rückmeldung geschlossen
